version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/data
    env_file:
      - .env

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  postgres_data:
